Check 71 - Create organization creation form on admin site
csuntechlab/checkpoint pull request #16
Opened 2019-03-13 21:08 UTC by digitalsoba

# Description
- Installed Vuetify
- Added Nav bar
- Added Signup page
- Update router

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- Load up your environment `docker-compose up -d`
- Run yarn
- Run `yarn run dev`
- Visit [http://localhost:8080](localhost:8080) and verify the sign up page matches the paper mockup

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2019-03-19 17:05 UTC, 404tonynotfound approved these changes

2019-03-19 17:53 UTC, 404tonynotfound requested changes

2019-03-19 17:53 UTC, 404tonynotfound commented on resources/js/router/index.js
> +import SignUp from '../views/SignUp.vue'
Can we put the signup component in router/views/signup/index.vue

2019-03-19 17:53 UTC, 404tonynotfound commented on resources/js/views/SignUp.vue
> +    organization: "",
we should make these null by default instead of empty strings

2019-03-19 17:53 UTC, 404tonynotfound commented on resources/js/views/SignUp.vue
> +  name: "SignUp"
name is usually not necessary if the filename is the same

2019-03-19 17:53 UTC, 404tonynotfound commented on resources/sass/_variables.scss
> +// $font-size-base: 0.9rem;
lets just remove these commented lines

2019-03-19 17:53 UTC, 404tonynotfound commented on resources/sass/app.scss
> +// @import url('https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons');
same here we can remove this

2019-03-19 17:53 UTC, 404tonynotfound commented on resources/views/index.blade.php
> +  <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons' rel="stylesheet">
I don't think we need these fonts right now

2019-03-26 18:31 UTC, 404tonynotfound approved these changes

2019-03-29 22:03 UTC, JayJayAquino approved these changes
👍

2019-03-29 22:03 UTC, merged