CHECK-168 -- BE: Remove unnecessary exceptions
csuntechlab/checkpoint pull request #42
Opened 2019-05-03 18:12 UTC by ChanM0

# Description

Please include a summary of the change and which issue is fixed. 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2019-05-10 20:22 UTC, JayJayAquino requested changes

2019-05-10 20:22 UTC, JayJayAquino commented on app/DomainValueObjects/Location/Location.php
> +    string $uuid = null,
why are we no longer type-hinting UUID?

2019-05-10 20:22 UTC, JayJayAquino commented on app/DomainValueObjects/Location/Location.php
> +    string $uuid = null,
see above

2019-05-10 20:22 UTC, JayJayAquino commented on app/Services/RegisterAdminService.php
> +      dd($e);
why we data dumping

2019-05-10 20:22 UTC, JayJayAquino commented on database/factories/ProgramFactory.php
>      $name = "backend";
why are we hard-coding backend

2019-05-13 17:20 UTC, 404tonynotfound approved these changes

2019-05-13 17:20 UTC, 404tonynotfound commented on app/DomainValueObjects/Location/Location.php
> +    string $uuid = null,
+1

2019-05-13 17:20 UTC, 404tonynotfound commented on app/Exceptions/AuthExceptions/UnauthorizedUser.php
> -namespace App\Exceptions\UserPorfileExceptions;
just want to point out porfile lol

2019-05-17 17:43 UTC, ChanM0 commented on app/DomainValueObjects/Location/Location.php
> +    string $uuid = null,
cause its unnecessary

2019-05-17 18:16 UTC, chippingcolt approved these changes

2019-05-17 18:22 UTC, JayJayAquino approved these changes
:+1:

2019-05-30 18:09 UTC, merged